# Generated by Django 2.2.3 on 2019-07-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_date',
        ),
    ]
