# Generated by Django 2.2.1 on 2019-05-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20190526_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
